//! Auth REST facets — API surfaces for different consumers.
//!
//! `data/` facet exposes all resources with full access, controlled by IAM.

use openerp_dsl_macro::facet;

// The facet macro generates router functions that reference *Store types.
// These are generated by #[persistent] in persistent.rs.
use crate::persistent::{
    UserStore, RoleStore, GroupStore, PolicyStore, SessionStore, ProviderStore,
};

// ── Data facet: full access ──

#[facet(path = "/data", auth = "jwt", model = "User")]
pub struct DataUser {
    #[readonly]
    pub id: String,
    pub name: String,
    pub email: Option<String>,
    pub avatar: Option<String>,
    pub active: bool,
    #[readonly]
    pub created_at: Option<String>,
    #[readonly]
    pub updated_at: Option<String>,
}

#[facet(path = "/data", auth = "jwt", model = "Role")]
pub struct DataRole {
    pub id: String,
    pub description: Option<String>,
    pub permissions: Vec<String>,
    pub service: Option<String>,
    #[readonly]
    pub created_at: Option<String>,
    #[readonly]
    pub updated_at: Option<String>,
}

#[facet(path = "/data", auth = "jwt", model = "Group")]
pub struct DataGroup {
    #[readonly]
    pub id: String,
    pub name: String,
    pub description: Option<String>,
    pub parent_id: Option<String>,
    pub external_source: Option<String>,
    pub external_id: Option<String>,
    #[readonly]
    pub created_at: Option<String>,
    #[readonly]
    pub updated_at: Option<String>,
}

#[facet(path = "/data", auth = "jwt", model = "Policy")]
pub struct DataPolicy {
    #[readonly]
    pub id: String,
    pub who: String,
    pub what: String,
    pub how: String,
    pub expires_at: Option<String>,
    #[readonly]
    pub created_at: Option<String>,
    #[readonly]
    pub updated_at: Option<String>,
}

#[facet(path = "/data", auth = "jwt", model = "Session")]
pub struct DataSession {
    #[readonly]
    pub id: String,
    pub user_id: String,
    #[readonly]
    pub issued_at: String,
    #[readonly]
    pub expires_at: String,
    pub revoked: bool,
    pub user_agent: Option<String>,
    pub ip_address: Option<String>,
}

#[facet(path = "/data", auth = "jwt", model = "Provider")]
pub struct DataProvider {
    pub id: String,
    pub name: String,
    pub provider_type: String,
    pub client_id: String,
    pub auth_url: String,
    pub token_url: String,
    pub userinfo_url: Option<String>,
    pub scopes: Vec<String>,
    pub redirect_url: String,
    pub enabled: bool,
    #[readonly]
    pub created_at: Option<String>,
    #[readonly]
    pub updated_at: Option<String>,
}
