// Flux FFI — C header for cross-platform bindings.
// Golden test: hand-written. Production: auto-generated by codegen.

#ifndef FLUX_FFI_H
#define FLUX_FFI_H

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

// Opaque handle to a Flux instance.
typedef struct FluxHandle FluxHandle;

// Byte buffer returned from FFI calls.
typedef struct {
    const uint8_t *ptr;
    size_t len;
} FluxBytes;

// Subscription callback.
// Called with (path, json_data, json_len, user_data).
typedef void (*FluxCallback)(
    const char *path,
    const uint8_t *data,
    size_t data_len,
    void *user_data
);

// ── Lifecycle ──

// Create a new Flux instance with Twitter BFF + demo data.
FluxHandle *flux_create(void);

// Free a Flux handle.
void flux_free(FluxHandle *handle);

// ── State ──

// Get state at path as JSON bytes.
// Returns { NULL, 0 } if not found.
// Caller must free with flux_bytes_free().
FluxBytes flux_get(const FluxHandle *handle, const char *path);

// Free bytes returned by flux_get.
void flux_bytes_free(FluxBytes bytes);

// ── Requests ──

// Emit a request with JSON payload.
// payload_json can be NULL for parameterless requests.
void flux_emit(FluxHandle *handle, const char *path, const char *payload_json);

// ── Subscriptions ──

// Subscribe to state changes matching a pattern.
// Returns subscription ID.
uint64_t flux_subscribe(
    FluxHandle *handle,
    const char *pattern,
    FluxCallback callback,
    void *user_data
);

// Unsubscribe.
void flux_unsubscribe(FluxHandle *handle, const char *pattern, uint64_t sub_id);

#ifdef __cplusplus
}
#endif

#endif // FLUX_FFI_H
