// FluxBridge — Swift wrapper around Flux C FFI.
// Golden test: hand-written. Production: auto-generated by codegen.

import Foundation

/// Main interface to the Flux state engine from Swift.
/// Wraps the C FFI and provides typed, Combine-friendly APIs.
@MainActor
final class FluxStore: ObservableObject {

    private let handle: OpaquePointer

    /// All state change notifications published here.
    /// SwiftUI views observe this to re-render.
    @Published private(set) var revision: UInt64 = 0

    init() {
        handle = flux_create()!
    }

    deinit {
        flux_free(handle)
    }

    // MARK: - State

    /// Get state at a path, decoded as T.
    func get<T: Decodable>(_ path: String) -> T? {
        let bytes = flux_get(handle, path)
        defer { flux_bytes_free(bytes) }
        guard let ptr = bytes.ptr, bytes.len > 0 else { return nil }
        let data = Data(bytes: ptr, count: bytes.len)
        return try? JSONDecoder().decode(T.self, from: data)
    }

    // MARK: - Requests

    /// Emit a request (fire-and-forget, blocks until handler completes).
    func emit(_ path: String, payload: Encodable? = nil) {
        let json: String?
        if let payload = payload {
            if let data = try? JSONEncoder().encode(AnyEncodable(payload)) {
                json = String(data: data, encoding: .utf8)
            } else {
                json = nil
            }
        } else {
            json = nil
        }
        flux_emit(handle, path, json)
        // Bump revision to trigger SwiftUI updates.
        revision += 1
    }

    /// Emit a request with a JSON dictionary.
    func emit(_ path: String, json: [String: Any]) {
        if let data = try? JSONSerialization.data(withJSONObject: json),
           let str = String(data: data, encoding: .utf8) {
            flux_emit(handle, path, str)
            revision += 1
        }
    }

    /// Emit a parameterless request.
    func emit(_ path: String) {
        flux_emit(handle, path, nil)
        revision += 1
    }
}

// MARK: - AnyEncodable helper

private struct AnyEncodable: Encodable {
    private let _encode: (Encoder) throws -> Void

    init(_ value: Encodable) {
        _encode = { encoder in
            try value.encode(to: encoder)
        }
    }

    func encode(to encoder: Encoder) throws {
        try _encode(encoder)
    }
}
