//! Twitter server module — DSL-driven backend, all in-memory.
//!
//! Models defined in `dsl/model/` via `#[model]` macro.
//! Standard CRUD auto-generated by `admin_kv_router`.
//! Custom hooks in `store_impls`.

#[path = "../dsl/model/mod.rs"]
pub mod model;

#[path = "../dsl/rest/app.rs"]
pub mod rest_app;

pub mod store_impls;
pub mod jwt;
pub mod i18n;
pub mod facet_handlers;

use std::sync::Arc;

use axum::Router;
use openerp_store::{admin_kv_router, HierarchyNode, KvOps, ModuleDef, ResourceDef};

use model::*;

/// Build the admin router for all Twitter resources.
///
/// Auto-generates standard CRUD for each model:
///   GET /{plural}         — list
///   GET /{plural}/{id}    — get
///   POST /{plural}        — create
///   PUT /{plural}/{id}    — update
///   DELETE /{plural}/{id} — delete
pub fn admin_router(
    kv: Arc<dyn openerp_kv::KVStore>,
    auth: Arc<dyn openerp_core::Authenticator>,
) -> Router {
    let mut router = Router::new();

    router = router.merge(admin_kv_router(
        KvOps::<User>::new(kv.clone()), auth.clone(),
        "twitter", "users", "user",
    ));
    router = router.merge(admin_kv_router(
        KvOps::<Tweet>::new(kv.clone()), auth.clone(),
        "twitter", "tweets", "tweet",
    ));
    router = router.merge(admin_kv_router(
        KvOps::<Like>::new(kv.clone()), auth.clone(),
        "twitter", "likes", "like",
    ));
    router = router.merge(admin_kv_router(
        KvOps::<Follow>::new(kv.clone()), auth.clone(),
        "twitter", "follows", "follow",
    ));

    router
}

/// Build schema definition from DSL model IR.
pub fn schema_def() -> ModuleDef {
    ModuleDef {
        id: "twitter",
        label: "Twitter",
        icon: "message-circle",
        resources: vec![
            ResourceDef::from_ir("twitter", User::__dsl_ir())
                .with_desc("User accounts"),
            ResourceDef::from_ir("twitter", Tweet::__dsl_ir())
                .with_desc("Tweets (posts)"),
            ResourceDef::from_ir("twitter", Like::__dsl_ir())
                .with_desc("Like records"),
            ResourceDef::from_ir("twitter", Follow::__dsl_ir())
                .with_desc("Follow relationships"),
        ],
        hierarchy: hierarchy(),
    }
}

/// Resource hierarchy for the sidebar.
fn hierarchy() -> Vec<HierarchyNode> {
    vec![
        HierarchyNode {
            resource: "user",
            label: "Users",
            icon: "users",
            description: "User accounts",
            children: vec![
                HierarchyNode::leaf("follow", "Follows", "user-plus", "Follow relationships"),
            ],
        },
        HierarchyNode {
            resource: "tweet",
            label: "Tweets",
            icon: "message-circle",
            description: "Tweets (posts)",
            children: vec![
                HierarchyNode::leaf("like", "Likes", "heart", "Like records"),
            ],
        },
    ]
}
